project_id = "sable-crown"

[functions.resolve-turn]
verify_jwt = true

[functions.username-auth]
verify_jwt = false

[functions.account-recovery]
verify_jwt = false

[functions.create-campaign]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.generate-narration]
verify_jwt = true
