const entry = { type: 'object', additionalProperties: false, required: ['id','name','description'], properties: { id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' } } };
const entries = { type: 'array', minItems: 1, items: entry };
export const detailedWorldSchema = {
  type: 'object', additionalProperties: false,
  required: ['metadata','premise','tone','factions','locations','cultures','history','characterOptions','items','rules','npcs','secrets','scenarioHooks','aiGuidance','safetyBoundaries','openingScenario','characterProfiles','worldEvents','secretSystems'],
  properties: {
    metadata: { type: 'object', additionalProperties: false, required: ['title','tagline','description','contentRating'], properties: { title: { type: 'string' }, tagline: { type: 'string' }, description: { type: 'string' }, contentRating: { type: 'string', enum: ['mature-no-explicit-sex'] } } },
    premise: { type: 'string' }, tone: { type: 'array', minItems: 1, items: { type: 'string' } }, factions: entries, locations: entries, cultures: entries, history: { type: 'array', minItems: 1, items: { type: 'string' } },
    characterOptions: { type: 'object', additionalProperties: false, required: ['backgrounds','strengths','weaknesses','motivations'], properties: { backgrounds: entries, strengths: entries, weaknesses: entries, motivations: entries } },
    items: entries, rules: { type: 'array', minItems: 1, items: { type: 'string' } }, npcs: { ...entries, minItems: 12 }, secrets: entries, scenarioHooks: entries,
    aiGuidance: { type: 'array', minItems: 1, items: { type: 'string' } }, safetyBoundaries: { type: 'array', minItems: 1, items: { type: 'string' } },
    openingScenario: { type: 'object', additionalProperties: false, required: ['id','title','chapterLabel','narration','startLocationId','startingInventory','memories','unresolvedThreads','sceneFacts','suggestions','relationships','characterConnections','relationshipRoles','calendar','playerPreset'], properties: {
      id: { type: 'string' }, title: { type: 'string' }, chapterLabel: { type: 'string' }, narration: { type: 'string' }, startLocationId: { type: 'string' }, startingInventory: { type: 'array', items: { type: 'string' } }, memories: { type: 'array', items: { type: 'string' } }, unresolvedThreads: { type: 'array', items: { type: 'string' } }, sceneFacts: { type: 'array', items: { type: 'string' } }, suggestions: { type: 'array', minItems: 3, maxItems: 3, items: { type: 'string' } }, relationships: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['name','score'], properties: { name: { type: 'string' }, score: { type: 'number', minimum: -100, maximum: 100 } } } },
      characterConnections: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['sourceId','targetId','relationshipType','status','private','reason'], properties: { sourceId: { type: 'string' }, targetId: { type: 'string' }, relationshipType: { type: 'string', minLength: 2, maxLength: 60 }, status: { type: 'string', enum: ['active','former'] }, private: { type: 'boolean' }, reason: { type: 'string', minLength: 3, maxLength: 1000 } } } },
      relationshipRoles: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['entityName','relationshipType','private','reason'], properties: { entityName:{type:'string'},relationshipType:{type:'string'},private:{type:'boolean'},reason:{type:'string'} } } },
      calendar: { type: 'object', additionalProperties: false, required: ['name','year','day','segment'], properties: { name: { type: 'string' }, year: { type: 'string' }, day: { type: 'integer', minimum: 1 }, segment: { type: 'string' } } },
      playerPreset: { type: 'object', additionalProperties: false, required: ['name','pronouns','backgroundId','strengthId','weaknessId','motivationId'], properties: { name: { type: 'string' }, pronouns: { type: 'string' }, backgroundId: { type: 'string' }, strengthId: { type: 'string' }, weaknessId: { type: 'string' }, motivationId: { type: 'string' } } },
    } },
    characterProfiles: { type: 'array', minItems: 12, items: { type: 'object', additionalProperties: false, required: ['npcId','startingLocation','values','goals','loyalties','canonBehaviors','persuasion'], properties: { npcId: { type: 'string' }, startingLocation: { type: 'object', additionalProperties: false, required: ['locationId','confidence','reason'], properties: { locationId: { type: 'string' }, confidence: { type: 'string', enum: ['low','medium','high','confirmed'] }, reason: { type: 'string' } } }, values: { type: 'array', minItems: 1, items: { type: 'string' } }, goals: { type: 'array', minItems: 1, items: { type: 'string' } }, loyalties: { type: 'array', items: { type: 'string' } }, canonBehaviors: { type: 'array', minItems: 1, items: { type: 'string' } }, persuasion: { type: 'object', additionalProperties: false, required: ['baseDifficulty','leverage','relationshipThresholds'], properties: { baseDifficulty: { type: 'string', enum: ['easy','moderate','hard','extreme'] }, leverage: { type: 'array', items: { type: 'string' } }, relationshipThresholds: { type: 'object', additionalProperties: false, required: ['cooperative','majorRisk'], properties: { cooperative: { type: 'integer', minimum: -100, maximum: 100 }, majorRisk: { type: 'integer', minimum: -100, maximum: 100 } } } } } } } },
    worldEvents: { type: 'array', minItems: 6, items: { type: 'object', additionalProperties: false, required: ['id','name','description','earliestDay','latestDay','conditions'], properties: { id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, earliestDay: { type: 'integer', minimum: 1 }, latestDay: { type: 'integer', minimum: 1 }, conditions: { type: 'array', items: { type: 'string' } } } } },
    secretSystems: { type: 'array', minItems: 1, items: { type: 'object', additionalProperties: false, required: ['id','name','description','stakes','initialAwareness','evidenceTypes'], properties: { id: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, stakes: { type: 'array', minItems: 1, items: { type: 'string' } }, initialAwareness: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['entityId','level','suspicion'], properties: { entityId: { type: 'string' }, level: { type: 'string', enum: ['none','suspects','knows'] }, suspicion: { type: 'integer', minimum: 0, maximum: 100 } } } }, evidenceTypes: { type: 'array', minItems: 1, items: { type: 'string' } } } } },
  },
};

